import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/catalogos.dart';
import '../services/session_service.dart';

class LanguageProvider extends ChangeNotifier {
  static const _prefsLanguageCodeKey = 'feriando_current_language_code';
  static const _prefsLanguageIdKey = 'feriando_current_language_id';

  static const supportedLanguages = <Idioma>[
    Idioma(idiomaID: 1, nombre: 'Español', codigo: 'es'),
    Idioma(idiomaID: 2, nombre: 'Mískito', codigo: 'miq'),
    Idioma(idiomaID: 3, nombre: 'Mayangna (Sumu)', codigo: 'yan'),
    Idioma(idiomaID: 4, nombre: 'Creole', codigo: 'jam'),
    Idioma(idiomaID: 5, nombre: 'Garífuna', codigo: 'cab'),
    Idioma(idiomaID: 6, nombre: 'Rama', codigo: 'rma'),
  ];

  static const supportedMaterialLanguageCodes = <String>['es'];

  LanguageProvider() {
    cargarIdiomaPreferido();
  }

  String currentLanguageCode = 'es';
  int currentIdiomaId = 1;

  Idioma _selectedLanguage = supportedLanguages.first;

  Idioma get selectedLanguage => _selectedLanguage;

  static const Map<String, Map<String, String>> _translations = {
    'es': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_phone': 'Número de teléfono',
      'register_email_optional': 'Correo (opcional)',
      'register_password': 'Contraseña',
      'register_department': 'Departamento',
      'register_municipality': 'Municipio',
      'register_exact_address': 'Dirección exacta / Comarca',
      'register_gender': 'Género',
      'register_female': 'Femenino',
      'register_male': 'Masculino',
      'register_publish_swap': 'Voy a publicar productos para trueque',
      'register_publish_swap_subtitle': 'Puedes cambiarlo luego desde tu perfil',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_photo_updated': 'Foto de perfil actualizada',
      'profile_error': 'Error: ',
      'profile_trust': ' de confianza',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'validation_min_length': 'Debe tener al menos 6 caracteres',
      'category_label': 'Categoría',
      'enter_name': 'Nombre requerido',
      'invalid_quantity': 'Cantidad inválida',
      'publish_product_title': 'Publicar producto',
      'edit_product_title': 'Editar producto',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'miq': {
      'app_name': 'Feriando',
      'login_subtitle': 'Diara aibapaia mairin nani warkika',
      'login_phone': 'Teléfon nambar',
      'login_password': 'Sikret bilika',
      'login_button': 'Dimaia',
      'login_no_account': '¿Akaunt apu man? Paskaia',
      'login_error': 'Sip apu dimi kapia.',
      'register_title': 'Akaunt paskaia',
      'register_names': 'Ninanani',
      'register_lastnames': 'Nina aikanani',
      'register_phone': 'Teléfon nambar',
      'register_email_optional': 'Imeil (want kaka)',
      'register_password': 'Sikret bilika',
      'register_department': 'Dipatment',
      'register_municipality': 'Munisipi',
      'register_exact_address': 'Tasba pliska / Direksion',
      'register_gender': 'Gender',
      'register_female': 'Mairin',
      'register_male': 'Waikna',
      'register_publish_swap': 'Yang diara nani paski atkaia sali laka ba ra',
      'register_publish_swap_subtitle': 'Ningkara sip sma senj yama perfil wina',
      'register_create_account': 'Akaunt paskaia',
      'register_select_municipio': 'Man munisipi wahbi saka.',
      'register_select_department': 'Man dipatment wahbi saka',
      'register_select_municipio_label': 'Munisipi wahbi saka',
      'register_select_municipio_field': 'Munisipi',
      'register_select_department_field': 'Dipatment',
      'profile_title': 'Yang perfilki',
      'profile_photo_updated': 'Perfil lilkika senj munan',
      'profile_error': 'Trabil: ',
      'profile_trust': ' kaisa lukanka',
      'profile_edit': 'Perfil senj yama',
      'profile_language': 'Bila aisanka',
      'profile_logout': 'Takaia',
      'profile_phone': 'Teléfon',
      'profile_email': 'Imeil',
      'profile_department': 'Dipatment',
      'profile_municipality': 'Munisipi',
      'profile_role_productora': 'Diara Paskra',
      'profile_role_compradora': 'Diara Aiatkra',
      'validation_min_length': 'Yawan 6 kakarikter luhaia sa',
      'category_label': 'Kategori',
      'enter_name': 'Nina yabaia nit sa',
      'invalid_quantity': 'Iban ba kasak apu',
      'publish_product_title': 'Diara paskaia',
      'edit_product_title': 'Diara senj yama',
      'select_language_title': 'Bila aisanka wahbi saka',
      'select_language_subtitle': 'Diki kaisa bila wahbi sakaia bibilki',
      'home_catalog': 'Diara Nani',
      'home_my_products': 'Yang dukiara',
      'home_trades': 'Sali Laka',
      'home_profile': 'Yang Perfilki',
      'catalog_title': 'Sali Laka',
      'catalog_filter_location_tooltip': 'Pliska tasba wahbaia',
      'catalog_search_hint': 'Diara plikaia...',
      'catalog_clear_location': 'Pliska wahban swahkaia',
      'catalog_all': 'Baskaba',
      'catalog_no_products_title': 'Diara kumi sin apu na pliska ra',
      'catalog_no_products_message': 'Plikaia laka senj yama pliska ba ra.',
      'catalog_department': 'Dipatment',
      'catalog_municipality': 'Munisipi',
      'product_detail_title': 'Diara sturika',
      'product_not_found': 'Diara kumi sin sakba ras.',
      'product_description': 'Sturika',
      'product_seller': 'Diara Paskra',
      'product_offer': 'Diara yabaia:',
      'request_swap': 'Sali laka makabaia',
      'notifications_title': 'Warkis nani',
      'notifications_update_error': 'Sip apu kapia warkis senj yama.',
      'notifications_empty_title': 'Warkis apu',
      'notifications_empty_message': 'Na ra kaika sma sali laka sturika nani.',
      'edit_profile_error_fields': 'Baskaba pliska bangan yabaia nit sa',
      'edit_profile_saved': 'Perfil senj yabanganka pain aisan',
      'edit_profile_title': 'Perfil senj yama',
      'edit_profile_save_changes': 'Senj yabaika swakaia',
      'edit_profile_names': 'Ninanani',
      'edit_profile_lastnames': 'Nina aikanani',
      'edit_profile_phone': 'Teléfon',
      'edit_profile_email': 'Imeil',
      'edit_profile_address': 'Tasba pliska kasakkira',
      'confirm_delete_title': 'Diara sauhkaia',
      'confirm_delete_message': '¿Kasak lukisma sauhkaia "{name}"? Na ba sip apu muni kli sakbaia.',
      'cancel': 'Siauhbi sakaia',
      'delete': 'Sauhkaia',
      'product_deleted': 'Diara sauhkan sa.',
      'my_products_title': 'Yang Dukiara Nani',
      'my_products_empty_title': 'Diara kumi sin paska ras mai sa',
      'my_products_empty_message': 'Toka "Paskaia" diara pas warkika sali laka ra.',
      'publish_label': 'Paskaia',
      'edit_label': 'Senj yama',
      'publish_product_select_category_unit': 'Kategori bara iban wahbi saka.',
      'publish_product_select_department_municipality': 'Dipatment bara munisipi tasba pliska wahbi saka.',
      'publish_product_error_loading': 'Trabil sturi dukiara alkaia',
      'publish_product_retry': 'Kli yama',
      'publish_product_save_error': 'Sip apu kan diara swakaia.',
      'publish_images': 'Diara lilkika nani',
      'publish_select_images': 'Lilkika nani wahbi saka',
      'publish_images_selected': '{count} wahbi sakan',
      'publish_location': 'Diara tasba pliska',
      'offer_type': 'Atkanka laka',
      'publish_product_save': 'Senj yabaika swakaia',
      'publish_product_create': 'Diara paskaia',
      'product_name_label': 'Diara nina',
      'product_description_label': 'Sturika',
      'quantity_label': 'Iban',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Tasba / Direksion kasak (Want kaka)',
      'price_label': 'Atkanka prais (C\$)',
      'location_suggestion': 'Lugar alkaia kaisan',
      'location_suggestion_city': '{city}, {department} kulsika ra',
      'location_suggestion_department': '{department} kulsika ra',
      'send_request': 'Sturi makabaika blakaia',
      'request_trade_choose_offer': 'Wahbi saka dia diara mai yaba sma.',
      'request_trade_sent': 'Makabaika blakan sa. Yulang diara paskra mairin bila.',
      'request_trade_title': 'Sali laka makabaia',
      'request_trade_buy_directly': 'Atki sakaia siksikira',
      'request_trade_buy_directly_subtitle': 'Diara kumi yabaia malka ra atki saka',
      'request_trade_question': '¿Dia diara yaba sma sali laka ra?',
      'request_trade_no_products': 'Diara kumi sin man dukiam apu. Pas paskaia "Yang dukiara" wina.',
      'requesting_product': 'Man makabisma:',
      'request_location': 'Pliska:',
      'trades_rating_title': 'Sali laka kaisa laka',
      'trades_comment_optional': 'Aisanka (want kaka)',
      'send': 'Blakaia',
      'trades_thanks': '¡Tinki pali man lukanka dukiara!',
      'trades_title': 'Yang Sali Laka Nani',
      'trades_tab_received': 'Alkan nani',
      'trades_tab_sent': 'Blakan nani',
      'trades_no_received': 'Makabaika kumi sin alka ras sma',
      'trades_no_sent': 'Makabaika kumi sin blaka ras sma',
      'trades_no_received_message': 'Upla kumi man dukiara want kaka, na ra takbia.',
      'trades_no_sent_message': 'Diara nani kaika bara makaba pas sali laka.',
      'trades_with': 'Wal:',
      'trades_meeting_point': 'Lugar alkaia:',
      'reject': 'Makaia',
      'accept': 'Walaia',
      'request_accepted': 'Makabaika alkan sa.',
      'request_rejected': 'Makabaika makan sa.',
      'request_response_error': 'Sip apu kan bila aibaia.',
      'request_send_error': 'Sip apu kan makabaika blakaia.',
      'request_feedback_error': 'Sip apu kan lukanka blakaia.',
      'offer_trueque': 'Sali Laka',
      'offer_venta': 'Atkanka',
      'offer_ambos': 'Walwal',
    },
    'yan': {
      'app_name': 'Feriando',
      'login_subtitle': 'Di kalyang yal nani warkika',
      'login_phone': 'Teléfon nambar',
      'login_password': 'Paswod',
      'login_button': 'Wapnin',
      'login_no_account': '¿Kwentah awas ma? Yamyang',
      'login_error': 'Sip awas wapnin kat.',
      'register_title': 'Kwentah yamyang',
      'register_names': 'Nini balna',
      'register_lastnames': 'Faamli nini',
      'register_phone': 'Teléfon nambar',
      'register_email_optional': 'Koreo (want yai)',
      'register_password': 'Paswod',
      'register_department': 'Dipatment',
      'register_municipality': 'Munisipi',
      'register_exact_address': 'Tasba yang / Direksion',
      'register_gender': 'Jender',
      'register_female': 'Yal',
      'register_male': 'Alh',
      'register_publish_swap': 'Yang di balna puutnin kal kalyang dinki',
      'register_publish_swap_subtitle': 'Ningkara sip sma senj yamnin profil kau',
      'register_create_account': 'Kwentah yamyang',
      'register_select_municipio': 'Munisipi pasnin.',
      'register_select_department': 'Dipatment pasnin',
      'register_select_municipio_label': 'Munisipi pasnin',
      'register_select_municipio_field': 'Munisipi',
      'register_select_department_field': 'Dipatment',
      'profile_title': 'Yang nini',
      'profile_photo_updated': 'Lilkika senj yamna',
      'profile_error': 'Trabil: ',
      'profile_trust': ' talnin kasak',
      'profile_edit': 'Perfil senj yamnin',
      'profile_language': 'Yul',
      'profile_logout': 'Tinin',
      'profile_phone': 'Teléfon',
      'profile_email': 'Koreo',
      'profile_department': 'Dipatment',
      'profile_municipality': 'Munisipi',
      'profile_role_productora': 'Di Yamik Yal',
      'profile_role_compradora': 'Di Atkayang Yal',
      'validation_min_length': '6 letra awit luwaik sa',
      'category_label': 'Kategori',
      'enter_name': 'Nini yultik sa',
      'invalid_quantity': 'Bukulka kasak awas',
      'publish_product_title': 'Di balna yamyang',
      'edit_product_title': 'Di balna senj yamnin',
      'select_language_title': 'Yul pasnin',
      'select_language_subtitle': 'Diki kaisa yul pasnin yultik',
      'home_catalog': 'Di Balna',
      'home_my_products': 'Yang dinki',
      'home_trades': 'Kal Kalyang',
      'home_profile': 'Yang nini',
      'catalog_title': 'Kal Kalyang Maakit',
      'catalog_filter_location_tooltip': 'Tasba pasnin',
      'catalog_search_hint': 'Di balna yulnin...',
      'catalog_clear_location': 'Tasba pasna kawatnin',
      'catalog_all': 'Buhlut',
      'catalog_no_products_title': 'Di kumi awas ya tasba kau',
      'catalog_no_products_message': 'Yulnin tasba senj yamnin.',
      'catalog_department': 'Dipatment',
      'catalog_municipality': 'Munisipi',
      'product_detail_title': 'Di sturika',
      'product_not_found': 'Di kumi awas.',
      'product_description': 'Sturika',
      'product_seller': 'Di yamik yal',
      'product_offer': 'Aafaka:',
      'request_swap': 'Kal kalyang aasknin',
      'notifications_title': 'Notifikieshan',
      'notifications_update_error': 'Sip awas notifikieshan senj yamnin.',
      'notifications_empty_title': 'Notifikieshan awas',
      'notifications_empty_message': 'Kal kalyang balna yai kau talma.',
      'edit_profile_error_fields': 'Buhlut spiñs puihnin sa',
      'edit_profile_saved': 'Perfil kasak sauhna',
      'edit_profile_title': 'Perfil senj yamnin',
      'edit_profile_save_changes': 'Senj sauhkaik',
      'edit_profile_names': 'Nini balna',
      'edit_profile_lastnames': 'Faamli nini',
      'edit_profile_phone': 'Teléfon',
      'edit_profile_email': 'Koreo',
      'edit_profile_address': 'Tasba yang kasak',
      'confirm_delete_title': 'Di tiknin',
      'confirm_delete_message': '¿Kasak "{name}" tiknin sma? Dis sip awas kli luhnin.',
      'cancel': 'Kanselnin',
      'delete': 'Tiknin',
      'product_deleted': 'Di tikna sa.',
      'my_products_title': 'Yang Dinki Balna',
      'my_products_empty_title': 'Di kumi sin puutna awas sma',
      'my_products_empty_message': 'Diki "Puutnin" fos di kal kalyang kau.',
      'publish_label': 'Puutnin',
      'edit_label': 'Senj yamnin',
      'publish_product_select_category_unit': 'Kategori bara bukulka pasnin.',
      'publish_product_select_department_municipality': 'Dipatment bara munisipi pasnin.',
      'publish_product_error_loading': 'Trabil dietah alnin kau',
      'publish_product_retry': 'Kli yamnin',
      'publish_product_save_error': 'Sip awas di sauhkaik.',
      'publish_images': 'Di lilkika balna',
      'publish_select_images': 'Lilkika pasnin',
      'publish_images_selected': '{count} pasna',
      'publish_location': 'Di tasba pliska',
      'offer_type': 'Aafaka taip',
      'publish_product_save': 'Senj sauhkaik',
      'publish_product_create': 'Di balna yamyang',
      'product_name_label': 'Di nini',
      'product_description_label': 'Sturika',
      'quantity_label': 'Bukulka',
      'unit_label': 'Yuunit',
      'location_exact_optional': 'Kamyuniti / Direksion (want yai)',
      'price_label': 'Prais (C\$)',
      'location_suggestion': 'Kal alnin pliska',
      'location_suggestion_city': '{city}, {department} kulsika kau',
      'location_suggestion_department': '{department} kulsika kau',
      'send_request': 'Rikwes yulnin',
      'request_trade_choose_offer': 'Pasnin diski di yaba sma.',
      'request_trade_sent': 'Rikwes blakna. Yal ansa kaisa yulang.',
      'request_trade_title': 'Kal kalyang aasknin',
      'request_trade_buy_directly': 'Atkik siksikira',
      'request_trade_buy_directly_subtitle': 'Di aafanin malka ra atki',
      'request_trade_question': '¿Dia di aafama kal kalyang kau?',
      'request_trade_no_products': 'Di kumi dinki awas ma. Fos puutnin "Yang dinki" kau.',
      'requesting_product': 'Man aaskma:',
      'request_location': 'Pliska:',
      'trades_rating_title': 'Kal kalyang talnin',
      'trades_comment_optional': 'Yul aisanka (want yai)',
      'send': 'Blaknin',
      'trades_thanks': '¡Tinki pali reitin dukiara!',
      'trades_title': 'Yang Kal Kalyang Balna',
      'trades_tab_received': 'Alna balna',
      'trades_tab_sent': 'Blakna balna',
      'trades_no_received': 'Rikwes kumi alna awas sma',
      'trades_no_sent': 'Rikwes kumi blakna awas sma',
      'trades_no_received_message': 'Muih kumi di want kaka, na kau takbia.',
      'trades_no_sent_message': 'Di balna talnin bara fos kal kalyang aasknin.',
      'trades_with': 'Wal:',
      'trades_meeting_point': 'Kal alnin pliska:',
      'reject': 'Diwasnin',
      'accept': 'Wasnin',
      'request_accepted': 'Rikwes wasna sa.',
      'request_rejected': 'Rikwes diwasna sa.',
      'request_response_error': 'Sip awas yul yabaik.',
      'request_send_error': 'Sip awas rikwes blaknin.',
      'request_feedback_error': 'Sip awas talnin blaknin.',
      'offer_trueque': 'Kal kalyang',
      'offer_venta': 'Atkanka',
      'offer_ambos': 'Buhlut',
    },
    'jam': {
      'app_name': 'Feriando',
      'login_subtitle': 'Chaynj op wid wuman powa',
      'login_phone': 'Foon nomba',
      'login_password': 'Paaswod',
      'login_button': 'Sain iin',
      'login_no_account': 'No gat akount yet? Miek wan',
      'login_error': 'Kudn sain iin rait nou.',
      'register_title': 'Miek akount',
      'register_names': 'Fos niem',
      'register_lastnames': 'Faamli niem',
      'register_phone': 'Foon nomba',
      'register_email_optional': 'Emeil (if yu waan)',
      'register_password': 'Paaswod',
      'register_department': 'Dipaatment',
      'register_municipality': 'Tong / Munisipality',
      'register_exact_address': 'Ezakt adres / Kamyuniti',
      'register_gender': 'Jenda',
      'register_female': 'Fiimiel',
      'register_male': 'Miel',
      'register_publish_swap': 'A gweyn puut op mi prodokts fi swap',
      'register_publish_swap_subtitle': 'Yu kyan chaynj it lieta ina yu profeil',
      'register_create_account': 'Miek akount',
      'register_select_municipio': 'Pik out yu tong / munisipality.',
      'register_select_department': 'Pik out yu dipaatment',
      'register_select_municipio_label': 'Pik out yu tong',
      'register_select_municipio_field': 'Tong',
      'register_select_department_field': 'Dipaatment',
      'profile_title': 'Mi Profeil',
      'profile_photo_updated': 'Profeil pikcha opdietid gud',
      'profile_error': 'Era: ',
      'profile_trust': ' chros reit',
      'profile_edit': 'Chenj profeil',
      'profile_language': 'Langwij',
      'profile_logout': 'Sain out',
      'profile_phone': 'Foon',
      'profile_email': 'Emeil',
      'profile_department': 'Dipaatment',
      'profile_municipality': 'Tong',
      'profile_role_productora': 'Faama Wuman',
      'profile_role_compradora': 'Baiya',
      'validation_min_length': 'Mos gat at liis 6 leta ar nomba',
      'category_label': 'Kiatigori',
      'enter_name': 'Niem rikwaird',
      'invalid_quantity': 'Rong amount',
      'publish_product_title': 'Puut op prodokt',
      'edit_product_title': 'Chenj prodokt',
      'select_language_title': 'Pik out langwij',
      'select_language_subtitle': 'Toch fi chuuz yu langwij',
      'home_catalog': 'Katalog',
      'home_my_products': 'Mi Prodokts',
      'home_trades': 'Swaps',
      'home_profile': 'Profeil',
      'catalog_title': 'Di Swap Maakit',
      'catalog_filter_location_tooltip': 'Filta bai plies',
      'catalog_search_hint': 'Luk fi prodokts...',
      'catalog_clear_location': 'Kliir plies filta',
      'catalog_all': 'Aal af dem',
      'catalog_no_products_title': 'No prodokt roun ya',
      'catalog_no_products_message': 'Chrai chenj di saach ar pik anada plies.',
      'catalog_department': 'Dipaatment',
      'catalog_municipality': 'Tong',
      'product_detail_title': 'Prodokt diitielz',
      'product_not_found': 'Prodokt no fain.',
      'product_description': 'Diskripshan',
      'product_seller': 'Projuusa',
      'product_offer': 'Aafa:',
      'request_swap': 'Aask fi swap',
      'notifications_title': 'Notifikieshan',
      'notifications_update_error': 'Kudn opdiet di notifikieshan.',
      'notifications_empty_title': 'No notifikieshan',
      'notifications_empty_message': 'Wen yu swap kom iin, yu gweyn si it ya.',
      'edit_profile_error_fields': 'Pliz fil out aal di rikwaird spiñs',
      'edit_profile_saved': 'Profeil siev op gud',
      'edit_profile_title': 'Chenj profeil',
      'edit_profile_save_changes': 'Siev chenjez',
      'edit_profile_names': 'Fos niem',
      'edit_profile_lastnames': 'Faamli niem',
      'edit_profile_phone': 'Foon',
      'edit_profile_email': 'Emeil',
      'edit_profile_address': 'Ezakt adres',
      'confirm_delete_title': 'Tek aaf prodokt',
      'confirm_delete_message': 'Yu sho yu waan diliit "{name}"? Dis kyan no get baak.',
      'cancel': 'Kiansl',
      'delete': 'Diliit',
      'product_deleted': 'Prodokt diliitid.',
      'my_products_title': 'Mi Prodokts',
      'my_products_empty_title': 'Yu nebba puut op notn yet',
      'my_products_empty_message': 'Toch "Puut op" fi aafa yu fos prodokt ina swap.',
      'publish_label': 'Puut op',
      'edit_label': 'Chenj',
      'publish_product_select_category_unit': 'Pik out kiatigori an yuunit.',
      'publish_product_select_department_municipality': 'Pik out dipaatment an tong plies.',
      'publish_product_error_loading': 'Era wen luodin di dietah',
      'publish_product_retry': 'Chrai agen',
      'publish_product_save_error': 'Kudn siev di prodokt.',
      'publish_images': 'Prodokt pikchaz',
      'publish_select_images': 'Pik pikchaz',
      'publish_images_selected': '{count} pikt out',
      'publish_location': 'Prodokt plies',
      'offer_type': 'Aafa taip',
      'publish_product_save': 'Siev chenjez',
      'publish_product_create': 'Puut op prodokt',
      'product_name_label': 'Prodokt niem',
      'product_description_label': 'Diskripshan',
      'quantity_label': 'Amount',
      'unit_label': 'Yuunit',
      'location_exact_optional': 'Kamyuniti / Ezakt adres (If yu waan)',
      'price_label': 'Refrans prais (C\$)',
      'location_suggestion': 'Sugjeshtid miitin plies',
      'location_suggestion_city': 'Dountong {city}, {department}',
      'location_suggestion_department': 'Sentral plies ina {department}',
      'send_request': 'Sen rikwes',
      'request_trade_choose_offer': 'Chuuz wich prodokt yu aafa fi trade.',
      'request_trade_sent': 'Rikwes sen aaf. Wet fi di projuusa ansa.',
      'request_trade_title': 'Aask fi swap',
      'request_trade_buy_directly': 'Bai it schriet',
      'request_trade_buy_directly_subtitle': 'Insted a aafa wan prodokt fi swap',
      'request_trade_question': 'Wich prodokt yu aafa ina trade?',
      'request_trade_no_products': 'Yu no gat no prodokts yet. Fos puut op wan ina "Mi Prodokts".',
      'requesting_product': 'Yu aask fi:',
      'request_location': 'Plies:',
      'trades_rating_title': 'Reit di swap',
      'trades_comment_optional': 'Koment (if yu waan)',
      'send': 'Sen',
      'trades_thanks': '¡Tenk yu fi yu reitin!',
      'trades_title': 'Mi Swaps',
      'trades_tab_received': 'Get iin',
      'trades_tab_sent': 'Sen aaf',
      'trades_no_received': 'Yu no get no swap rikwes yet',
      'trades_no_sent': 'Yu nebba sen no swap rikwes yet',
      'trades_no_received_message': 'Wen smadi waan yu prodokt, it gweyn shuo op ya.',
      'trades_no_sent_message': 'Saach di katalog an aask fi yu fos swap.',
      'trades_with': 'Wid:',
      'trades_meeting_point': 'Miitin plies:',
      'reject': 'Rijek',
      'accept': 'Aksep',
      'request_accepted': 'Swap rikwes akseptid.',
      'request_rejected': 'Swap rikwes rijektid.',
      'request_response_error': 'Kudn ansa di rikwes.',
      'request_send_error': 'Kudn sen di rikwes.',
      'request_feedback_error': 'Kudn sen di reitin.',
      'offer_trueque': 'Swap',
      'offer_venta': 'Sel',
      'offer_ambos': 'Tuu af dem',
    },
    'cab': {
      'app_name': 'Feriando',
      'login_subtitle': 'Abaníchaguni tau hawagu hiñüñü',
      'login_phone': 'Numadün teléfonu',
      'login_password': 'Garuwidun',
      'login_button': 'Abaña',
      'login_no_account': '¿Mama buénta bu? Ariha cuenta',
      'login_error': 'Mabagaditi abainguni.',
      'register_title': 'Arufuda cuenta',
      'register_names': 'Iri',
      'register_lastnames': 'Fáamili iri',
      'register_phone': 'Numadün teléfonu',
      'register_email_optional': 'Kórêu (anhein busén)',
      'register_password': 'Garuwidun',
      'register_department': 'Dipataméntu',
      'register_municipality': 'Múnisípiu',
      'register_exact_address': 'Ubóu / Direksión',
      'register_gender': 'Hénêru',
      'register_female': 'Würi',
      'register_male': 'Wügüri',
      'register_publish_swap': 'Aluwagüda nuba nadagimehugu lidan abaníchaguni',
      'register_publish_swap_subtitle': 'Gayarati gasiruha lárigi lidan bupérfil',
      'register_create_account': 'Arufuda cuenta',
      'register_select_municipio': 'Aganba bumúnisípiun.',
      'register_select_department': 'Aganba budipataméntun',
      'register_select_municipio_label': 'Aganba bumúnisípiun',
      'register_select_municipio_field': 'Múnisípiu',
      'register_select_department_field': 'Dipataméntu',
      'profile_title': 'Nupérfil',
      'profile_photo_updated': 'Foto gasiruhawati lidan buida',
      'profile_error': 'Trabili: ',
      'profile_trust': ' uéseruni',
      'profile_edit': 'Gasiruha pérfil',
      'profile_language': 'Iñeñi',
      'profile_logout': 'Afayiduni',
      'profile_phone': 'Teléfonu',
      'profile_email': 'Kórêu',
      'profile_department': 'Dipataméntu',
      'profile_municipality': 'Múnisípiu',
      'profile_role_productora': 'Würi Adagimeti',
      'profile_role_compradora': 'Würi Afuruguti',
      'validation_min_length': 'Mosu liña 6 lítiara',
      'category_label': 'Katigori',
      'enter_name': 'Megeguati iri',
      'invalid_quantity': 'Míñaditi namburu',
      'publish_product_title': 'Aluwagüda nadagimein',
      'edit_product_title': 'Gasiruha nadagimein',
      'select_language_title': 'Aganba iñeñi',
      'select_language_subtitle': 'Tocha luagu buñeñin',
      'home_catalog': 'Idagüeti',
      'home_my_products': 'Nadagimehugu',
      'home_trades': 'Abaníchaguni',
      'home_profile': 'Nupérfil',
      'catalog_title': 'Abaníchaguni Maagatu',
      'catalog_filter_location_tooltip': 'Filtru ubóu',
      'catalog_search_hint': 'Aounwagüni nadagimehugu...',
      'catalog_clear_location': 'Limbya ubóu',
      'catalog_all': 'Sun',
      'catalog_no_products_title': 'Uwa nadagimein ya',
      'catalog_no_products_message': 'Gasiruha aounwagüni ubóu lidan.',
      'catalog_department': 'Dipataméntu',
      'catalog_municipality': 'Múnisípiu',
      'product_detail_title': 'Nadagimein tídangiñe',
      'product_not_found': 'Madarirúnti nadagimein.',
      'product_description': 'Adagimei sturi',
      'product_seller': 'Adagimeti',
      'product_offer': 'Afaiduni:',
      'request_swap': 'Alüküda abaníchaguni',
      'notifications_title': 'Notifikasión',
      'notifications_update_error': 'Mabagaditi gasiruni notifikasión.',
      'notifications_empty_title': 'Uwa notifikasión',
      'notifications_empty_message': 'Ariha buba abaníchaguni lídangiñe ya.',
      'edit_profile_error_fields': 'Megeguati sun lítiara',
      'edit_profile_saved': 'Pérfil aluwagüdawatu buida',
      'edit_profile_title': 'Gasiruha pérfil',
      'edit_profile_save_changes': 'Aluwagüda gasiruhuni',
      'edit_profile_names': 'Iri',
      'edit_profile_lastnames': 'Fáamili iri',
      'edit_profile_phone': 'Teléfonu',
      'edit_profile_email': 'Kórêu',
      'edit_profile_address': 'Ubóu kasak',
      'confirm_delete_title': 'Áfaraha nadagimein',
      'confirm_delete_message': '¿Inarün bafarahalíñe "{name}"? Siñati gürigua lárigi.',
      'cancel': 'Ansiha',
      'delete': 'Áfaraha',
      'product_deleted': 'Nadagimein afarúkouti.',
      'my_products_title': 'Nadagimehugu',
      'my_products_empty_title': 'Maluwagüdünbaditi nada yet',
      'my_products_empty_message': 'Tocha "Aluwagüda" bunadagimein lidan abaníchaguni.',
      'publish_label': 'Aluwagüda',
      'edit_label': 'Gasiruha',
      'publish_product_select_category_unit': 'Aganba katigori tau unidá.',
      'publish_product_select_department_municipality': 'Aganba dipataméntu tau múnisípiu.',
      'publish_product_error_loading': 'Trabili lidan dátu',
      'publish_product_retry': 'Kli adagimei',
      'publish_product_save_error': 'Siñati laluwagüdüni.',
      'publish_images': 'Nadagimein foto',
      'publish_select_images': 'Aganba foto',
      'publish_images_selected': '{count} aganbawati',
      'publish_location': 'Nadagimein ubóu',
      'offer_type': 'Afaiduni líkiti',
      'publish_product_save': 'Aluwagüda gasiruhuni',
      'publish_product_create': 'Aluwagüda nadagimein',
      'product_name_label': 'Nadagimein iri',
      'product_description_label': 'Sturi',
      'quantity_label': 'Namburu',
      'unit_label': 'Unidá',
      'location_exact_optional': 'Kamyuniti / Ubóu (anhein busén)',
      'price_label': 'Prais (C\$)',
      'location_suggestion': 'Ubóu abaníchaguni',
      'location_suggestion_city': 'Séntru {city}, {department}',
      'location_suggestion_department': 'Séntru ubóu lidan {department}',
      'send_request': 'Ábürüda alüküdüni',
      'request_trade_choose_offer': 'Aganba katei bíchuguba.',
      'request_trade_sent': 'Alüküdüni ábürüdawatu. Mabagadin adagimeti.',
      'request_trade_title': 'Alüküda abaníchaguni',
      'request_trade_buy_directly': 'Afurugu siksiki',
      'request_trade_buy_directly_subtitle': 'Girarügü bichuga katei lidan abaníchaguni',
      'request_trade_question': '¿Katai bíchuguba lidan abaníchaguni?',
      'request_trade_no_products': 'Uwa bunadagimein ya. Aluwagüda kaba lidan "Nadagimehugu".',
      'requesting_product': 'Balüküda ba:',
      'request_location': 'Ubóu:',
      'trades_rating_title': 'Ariha abaníchaguni',
      'trades_comment_optional': 'Dimurei (anhein busén)',
      'send': 'Ábürüda',
      'trades_thanks': '¡Seremein buarihan luagu!',
      'trades_title': 'Nabaníchaguni',
      'trades_tab_received': 'Güriguti',
      'trades_tab_sent': 'Ábürüdawati',
      'trades_no_received': 'Míbiri bu alüküdüni yet',
      'trades_no_sent': 'Mábürüdünbaditi alüküdüni yet',
      'trades_no_received_message': 'Dan le busénboun bunadagimein, ábürüdawa ya.',
      'trades_no_sent_message': 'Aounwagüni idagüeti alüküda bunadagimein.',
      'trades_with': 'Tau:',
      'trades_meeting_point': 'Ubóu abaníchaguni:',
      'reject': 'Magúnditina',
      'accept': 'Aúnabuti',
      'request_accepted': 'Alüküdüni aunabúwati.',
      'request_rejected': 'Alüküdüni magúnditina.',
      'request_response_error': 'Siñati yaban dimurei.',
      'request_send_error': 'Siñati ábürüda alüküdüni.',
      'request_feedback_error': 'Siñati ábürüda arihuni.',
      'offer_trueque': 'Abaníchaguni',
      'offer_venta': 'Afuruguni',
      'offer_ambos': 'Biama',
    },
    'rma': {
      'app_name': 'Feriando',
      'login_subtitle': 'Kuuk bang suuli yelk nani bang',
      'login_phone': 'Teléfon nambar',
      'login_password': 'Paswod',
      'login_button': 'Taabi',
      'login_no_account': '¿Kwentah unsu? Maki',
      'login_error': 'Taabi miking unsu.',
      'register_title': 'Kwentah maki',
      'register_names': 'Nii nani',
      'register_lastnames': 'Faamli nii',
      'register_phone': 'Teléfon nambar',
      'register_email_optional': 'Imeil (want tama)',
      'register_password': 'Paswod',
      'register_department': 'Dipatment',
      'register_municipality': 'Munisipi',
      'register_exact_address': 'Kriik pliis / Direksion',
      'register_gender': 'Jender',
      'register_female': 'Yelk',
      'register_male': 'Tawan',
      'register_publish_swap': 'Naing suuli maki kuuk bang dukiara',
      'register_publish_swap_subtitle': 'Ningkarku sip sma senj maki perfil kau',
      'register_create_account': 'Kwentah maki',
      'register_select_municipio': 'Munisipi pik.',
      'register_select_department': 'Dipatment pik',
      'register_select_municipio_label': 'Munisipi pik',
      'register_select_municipio_field': 'Munisipi',
      'register_select_department_field': 'Dipatment',
      'profile_title': 'Naing perfil',
      'profile_photo_updated': 'Foto senj bang',
      'profile_error': 'Trabil: ',
      'profile_trust': ' tal kasak',
      'profile_edit': 'Perfil senj',
      'profile_language': 'Yuu',
      'profile_logout': 'Yuuli',
      'profile_phone': 'Teléfon',
      'profile_email': 'Imeil',
      'profile_department': 'Dipatment',
      'profile_municipality': 'Munisipi',
      'profile_role_productora': 'Suuli Maker Yelk',
      'profile_role_compradora': 'Atkayang Yelk',
      'validation_min_length': '6 kakarikter luwaik',
      'category_label': 'Kategori',
      'enter_name': 'Nii yultik',
      'invalid_quantity': 'Suuli bukulk unsu',
      'publish_product_title': 'Suuli maki',
      'edit_product_title': 'Suuli senj',
      'select_language_title': 'Yuu pik',
      'select_language_subtitle': 'Toch yuu pik dukiara',
      'home_catalog': 'Suuli Muku',
      'home_my_products': 'Naing Suuli',
      'home_trades': 'Kuuk Bang',
      'home_profile': 'Naing Perfil',
      'catalog_title': 'Kuuk Bang Maakit',
      'catalog_filter_location_tooltip': 'Pliis pik',
      'catalog_search_hint': 'Suuli yulpu...',
      'catalog_clear_location': 'Pliis kliir',
      'catalog_all': 'Puu',
      'catalog_no_products_title': 'Suuli unsu ya pliis kau',
      'catalog_no_products_message': 'Yulpu pliis senj maki.',
      'catalog_department': 'Dipatment',
      'catalog_municipality': 'Munisipi',
      'product_detail_title': 'Suuli sturi',
      'product_not_found': 'Suuli unsu.',
      'product_description': 'Sturi',
      'product_seller': 'Maker Yelk',
      'product_offer': 'Aafaka:',
      'request_swap': 'Kuuk bang aask',
      'notifications_title': 'Notifikieshan',
      'notifications_update_error': 'Notifikieshan senj unsu.',
      'notifications_empty_title': 'Notifikieshan unsu',
      'notifications_empty_message': 'Kuuk bang ya kau talma.',
      'edit_profile_error_fields': 'Puu spiñs yultik',
      'edit_profile_saved': 'Perfil kasak yulbi',
      'edit_profile_title': 'Perfil senj',
      'edit_profile_save_changes': 'Yulbing',
      'edit_profile_names': 'Nii nani',
      'edit_profile_lastnames': 'Faamli nii',
      'edit_profile_phone': 'Teléfon',
      'edit_profile_email': 'Imeil',
      'edit_profile_address': 'Pliis kasak',
      'confirm_delete_title': 'Suuli bangkama',
      'confirm_delete_message': '¿Kasak "{name}" bangkama? Dis sip unsu kli sak.',
      'cancel': 'Kanseling',
      'delete': 'Bangkama',
      'product_deleted': 'Suuli bangka.',
      'my_products_title': 'Naing Suuli',
      'my_products_empty_title': 'Suuli maki unsu yet',
      'my_products_empty_message': 'Toch "Maki" fos suuli kuuk bang kau.',
      'publish_label': 'Maki',
      'edit_label': 'Senj',
      'publish_product_select_category_unit': 'Kategori bara yuunit pik.',
      'publish_product_select_department_municipality': 'Dipatment bara munisipi pik.',
      'publish_product_error_loading': 'Trabil dietah al kau',
      'publish_product_retry': 'Kli maki',
      'publish_product_save_error': 'Suuli yulbi unsu.',
      'publish_images': 'Suuli lilkika',
      'publish_select_images': 'Lilkika pik',
      'publish_images_selected': '{count} pikt',
      'publish_location': 'Suuli pliis',
      'offer_type': 'Aafaka taip',
      'publish_product_save': 'Yulbing',
      'publish_product_create': 'Suuli maki',
      'product_name_label': 'Suuli nii',
      'product_description_label': 'Sturi',
      'quantity_label': 'Bukulka',
      'unit_label': 'Yuunit',
      'location_exact_optional': 'Kamyuniti / Pliis (want tama)',
      'price_label': 'Prais (C\$)',
      'location_suggestion': 'Kuuk bang pliis',
      'location_suggestion_city': '{city}, {department} séntru',
      'location_suggestion_department': '{department} séntru',
      'send_request': 'Rikwes blak',
      'request_trade_choose_offer': 'Pik diski suuli yaba.',
      'request_trade_sent': 'Rikwes blaka. Yelk bila wait.',
      'request_trade_title': 'Kuuk bang aask',
      'request_trade_buy_directly': 'Atkama siksiki',
      'request_trade_buy_directly_subtitle': 'Suuli aafa malka ra atki',
      'request_trade_question': '¿Diski suuli aafama kuuk bang kau?',
      'request_trade_no_products': 'Suuli unsu. Fos maki "Naing Suuli" kau.',
      'requesting_product': 'Man aaskma:',
      'request_location': 'Pliis:',
      'trades_rating_title': 'Kuuk bang tal',
      'trades_comment_optional': 'Yuu aisanka (want tama)',
      'send': 'Blak',
      'trades_thanks': '¡Maik tiingki reiting dukiara!',
      'trades_title': 'Naing Kuuk Bang',
      'trades_tab_received': 'Alna',
      'trades_tab_sent': 'Blakna',
      'trades_no_received': 'Rikwes unsu yet',
      'trades_no_sent': 'Rikwes blak unsu yet',
      'trades_no_received_message': 'Muih suuli want kaka, ya kau takbia.',
      'trades_no_sent_message': 'Suuli tal bara fos kuuk bang aask.',
      'trades_with': 'Wal:',
      'trades_meeting_point': 'Kuuk bang pliis:',
      'reject': 'Taa malabi',
      'accept': 'Malabi',
      'request_accepted': 'Rikwes malabi.',
      'request_rejected': 'Rikwes taa malabi.',
      'request_response_error': 'Sip unsu ansa.',
      'request_send_error': 'Rikwes blak unsu.',
      'request_feedback_error': 'Reiting blak unsu.',
      'offer_trueque': 'Kuuk bang',
      'offer_venta': 'Atkama',
      'offer_ambos': 'Puu',
    },
  };

  Locale get locale => const Locale('es');

  String translate(String key) {
    final languageMap = _translations[_selectedLanguage.codigo];
    final selectedValue = languageMap?[key];
    if (selectedValue != null) {
      return selectedValue;
    }

    final fallbackValue = _translations['es']?[key];
    if (fallbackValue != null) {
      return fallbackValue;
    }

    return key;
  }

  Future<void> setLanguage(Idioma idioma) async {
    if (idioma.codigo.isEmpty) {
      return;
    }

    _selectedLanguage = idioma;
    currentLanguageCode = idioma.codigo;
    currentIdiomaId = idioma.idiomaID;

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsLanguageCodeKey, idioma.codigo);
    await prefs.setInt(_prefsLanguageIdKey, idioma.idiomaID);
    await SessionService.guardarIdiomaPreferidoID(idioma.idiomaID);

    notifyListeners();
  }

  Future<void> cargarIdiomaPreferido() async {
    final prefs = await SharedPreferences.getInstance();
    final preferred = await SessionService.obtenerIdiomaPreferidoID();
    final savedId = prefs.getInt(_prefsLanguageIdKey);
    final savedCode = prefs.getString(_prefsLanguageCodeKey);

    if (savedId != null || savedCode != null || preferred != null) {
      final resolvedID = savedId ?? preferred;
      final resolvedCode = savedCode ?? supportedLanguages.firstWhere(
        (language) => language.idiomaID == resolvedID,
        orElse: () => supportedLanguages.first,
      ).codigo;

      final idioma = supportedLanguages.firstWhere(
        (language) => language.idiomaID == resolvedID || language.codigo == resolvedCode,
        orElse: () => supportedLanguages.first,
      );

      _selectedLanguage = idioma;
      currentLanguageCode = idioma.codigo;
      currentIdiomaId = idioma.idiomaID;
      notifyListeners();
      return;
    }

    _selectedLanguage = supportedLanguages.first;
    currentLanguageCode = supportedLanguages.first.codigo;
    currentIdiomaId = supportedLanguages.first.idiomaID;
  }
}
