import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/catalogos.dart';
import '../services/session_service.dart';

class LanguageProvider extends ChangeNotifier {
  static const _prefsLanguageCodeKey = 'feriando_current_language_code';
  static const _prefsLanguageIdKey = 'feriando_current_language_id';

  static const supportedLanguages = <Idioma>[
    Idioma(idiomaID: 1, nombre: 'Español', codigo: 'es'),
    Idioma(idiomaID: 2, nombre: 'Mískito', codigo: 'miq'),
    Idioma(idiomaID: 3, nombre: 'Mayangna (Sumu)', codigo: 'yan'),
    Idioma(idiomaID: 4, nombre: 'Creole', codigo: 'jam'),
    Idioma(idiomaID: 5, nombre: 'Garífuna', codigo: 'cab'),
    Idioma(idiomaID: 6, nombre: 'Rama', codigo: 'rma'),
  ];

  static const supportedMaterialLanguageCodes = <String>['es'];

  LanguageProvider() {
    cargarIdiomaPreferido();
  }

  String currentLanguageCode = 'es';
  int currentIdiomaId = 1;

  Idioma _selectedLanguage = supportedLanguages.first;

  Idioma get selectedLanguage => _selectedLanguage;

  static const Map<String, Map<String, String>> _translations = {
    'es': {
      
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_phone': 'Número de teléfono',
      'register_email_optional': 'Correo (opcional)',
      'register_password': 'Contraseña',
      'register_department': 'Departamento',
      'register_municipality': 'Municipio',
      'register_exact_address': 'Dirección exacta / Comarca',
      'register_gender': 'Género',
      'register_female': 'Femenino',
      'register_male': 'Masculino',
      'register_publish_swap': 'Voy a publicar productos para trueque',
      'register_publish_swap_subtitle': 'Puedes cambiarlo luego desde tu perfil',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_photo_updated': 'Foto de perfil actualizada',
      'profile_error': 'Error: ',
      'profile_trust': ' de confianza',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'validation_min_length': 'Debe tener al menos 6 caracteres',
      'category_label': 'Categoría',
      'enter_name': 'Nombre requerido',
      'invalid_quantity': 'Cantidad inválida',
      'publish_product_title': 'Publicar producto',
      'edit_product_title': 'Editar producto',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'miq': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_email_optional': 'Correo (opcional)',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'yan': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_email_optional': 'Correo (opcional)',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'jam': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_email_optional': 'Correo (opcional)',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'cab': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_email_optional': 'Correo (opcional)',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
    'rma': {
      'app_name': 'Feriando',
      'login_subtitle': 'Intercambio con enfoque de género',
      'login_phone': 'Número de teléfono',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_error': 'No se pudo iniciar sesión.',
      'register_title': 'Crear cuenta',
      'register_names': 'Nombres',
      'register_lastnames': 'Apellidos',
      'register_email_optional': 'Correo (opcional)',
      'register_create_account': 'Crear cuenta',
      'register_select_municipio': 'Selecciona tu municipio.',
      'register_select_department': 'Selecciona tu departamento',
      'register_select_municipio_label': 'Selecciona tu municipio',
      'register_select_municipio_field': 'Municipio',
      'register_select_department_field': 'Departamento',
      'profile_title': 'Mi perfil',
      'profile_edit': 'Editar perfil',
      'profile_language': 'Idioma',
      'profile_logout': 'Cerrar sesión',
      'profile_phone': 'Teléfono',
      'profile_email': 'Correo',
      'profile_department': 'Departamento',
      'profile_municipality': 'Municipio',
      'profile_role_productora': 'Productora',
      'profile_role_compradora': 'Compradora',
      'select_language_title': 'Seleccionar idioma',
      'select_language_subtitle': 'Toca para elegir tu idioma preferido',
      'home_catalog': 'Catálogo',
      'home_my_products': 'Mis productos',
      'home_trades': 'Trueques',
      'home_profile': 'Perfil',
      'catalog_title': 'El Trueque',
      'catalog_filter_location_tooltip': 'Filtrar por ubicación',
      'catalog_search_hint': 'Buscar productos...',
      'catalog_clear_location': 'Limpiar ubicación',
      'catalog_all': 'Todas',
      'catalog_no_products_title': 'No hay productos por aquí',
      'catalog_no_products_message': 'Prueba ajustando los filtros de búsqueda o ubicación.',
      'catalog_department': 'Departamento',
      'catalog_municipality': 'Municipio',
      'product_detail_title': 'Detalle del producto',
      'product_not_found': 'No se encontró el producto.',
      'product_description': 'Descripción',
      'product_seller': 'Productor(a)',
      'product_offer': 'Oferta:',
      'request_swap': 'Solicitar trueque',
      'notifications_title': 'Notificaciones',
      'notifications_update_error': 'No se pudo actualizar la notificación.',
      'notifications_empty_title': 'Sin notificaciones',
      'notifications_empty_message': 'Aquí verás avisos sobre tus solicitudes de trueque.',
      'edit_profile_error_fields': 'Por favor completa todos los campos requeridos',
      'edit_profile_saved': 'Perfil actualizado exitosamente',
      'edit_profile_title': 'Editar perfil',
      'edit_profile_save_changes': 'Guardar cambios',
      'edit_profile_names': 'Nombres',
      'edit_profile_lastnames': 'Apellidos',
      'edit_profile_phone': 'Teléfono',
      'edit_profile_email': 'Correo',
      'edit_profile_address': 'Dirección exacta',
      'confirm_delete_title': 'Eliminar producto',
      'confirm_delete_message': '¿Seguro que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'product_deleted': 'Producto eliminado.',
      'my_products_title': 'Mis productos',
      'my_products_empty_title': 'Aún no has publicado nada',
      'my_products_empty_message': 'Toca "Publicar" para ofrecer tu primer producto en trueque.',
      'publish_label': 'Publicar',
      'edit_label': 'Editar',
      'publish_product_select_category_unit': 'Selecciona categoría y unidad de medida.',
      'publish_product_select_department_municipality': 'Selecciona el departamento y municipio de ubicación.',
      'publish_product_error_loading': 'Error cargando datos',
      'publish_product_retry': 'Reintentar',
      'publish_product_save_error': 'No se pudo guardar el producto.',
      'publish_images': 'Imágenes del producto',
      'publish_select_images': 'Seleccionar imágenes',
      'publish_images_selected': '{count} seleccionadas',
      'publish_location': 'Ubicación del producto',
      'offer_type': 'Tipo de oferta',
      'publish_product_save': 'Guardar cambios',
      'publish_product_create': 'Publicar producto',
      'product_name_label': 'Nombre del producto',
      'product_description_label': 'Descripción',
      'quantity_label': 'Cantidad',
      'unit_label': 'Unidad',
      'location_exact_optional': 'Comarca / Dirección exacta (Opcional)',
      'price_label': 'Precio referencial (C\$)',
      'location_suggestion': 'Lugar de encuentro sugerido',
      'location_suggestion_city': 'Centro de {city}, {department}',
      'location_suggestion_department': 'Punto céntrico en {department}',
      'send_request': 'Enviar solicitud',
      'request_trade_choose_offer': 'Elige qué producto vas a ofrecer.',
      'request_trade_sent': 'Solicitud enviada. Espera la respuesta de la productora.',
      'request_trade_title': 'Solicitar intercambio',
      'request_trade_buy_directly': 'Comprar directamente',
      'request_trade_buy_directly_subtitle': 'En vez de ofrecer un producto a cambio',
      'request_trade_question': '¿Qué producto ofreces a cambio?',
      'request_trade_no_products': 'No tienes productos disponibles. Publica uno primero desde "Mis productos".',
      'requesting_product': 'Vas a solicitar:',
      'request_location': 'Ubicación:',
      'trades_rating_title': 'Valorar intercambio',
      'trades_comment_optional': 'Comentario (opcional)',
      'send': 'Enviar',
      'trades_thanks': '¡Gracias por tu valoración!',
      'trades_title': 'Mis trueques',
      'trades_tab_received': 'Recibidas',
      'trades_tab_sent': 'Enviadas',
      'trades_no_received': 'No has recibido solicitudes',
      'trades_no_sent': 'No has enviado solicitudes',
      'trades_no_received_message': 'Cuando alguien quiera uno de tus productos, aparecerá aquí.',
      'trades_no_sent_message': 'Explora el catálogo y solicita tu primer trueque.',
      'trades_with': 'Con:',
      'trades_meeting_point': 'Punto de encuentro:',
      'reject': 'Rechazar',
      'accept': 'Aceptar',
      'request_accepted': 'Solicitud aceptada.',
      'request_rejected': 'Solicitud rechazada.',
      'request_response_error': 'No se pudo responder.',
      'request_send_error': 'No se pudo enviar la solicitud.',
      'request_feedback_error': 'No se pudo enviar la valoración.',
      'offer_trueque': 'Trueque',
      'offer_venta': 'Venta',
      'offer_ambos': 'Ambos',
    },
  };

  Locale get locale => const Locale('es');

  String translate(String key) {
    final languageMap = _translations[_selectedLanguage.codigo];
    final selectedValue = languageMap?[key];
    if (selectedValue != null) {
      return selectedValue;
    }

    final fallbackValue = _translations['es']?[key];
    if (fallbackValue != null) {
      return fallbackValue;
    }

    return key;
  }

  Future<void> setLanguage(Idioma idioma) async {
    if (idioma.codigo.isEmpty) {
      return;
    }

    _selectedLanguage = idioma;
    currentLanguageCode = idioma.codigo;
    currentIdiomaId = idioma.idiomaID;

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsLanguageCodeKey, idioma.codigo);
    await prefs.setInt(_prefsLanguageIdKey, idioma.idiomaID);
    await SessionService.guardarIdiomaPreferidoID(idioma.idiomaID);

    notifyListeners();
  }

  Future<void> cargarIdiomaPreferido() async {
    final prefs = await SharedPreferences.getInstance();
    final preferred = await SessionService.obtenerIdiomaPreferidoID();
    final savedId = prefs.getInt(_prefsLanguageIdKey);
    final savedCode = prefs.getString(_prefsLanguageCodeKey);

    if (savedId != null || savedCode != null || preferred != null) {
      final resolvedID = savedId ?? preferred;
      final resolvedCode = savedCode ?? supportedLanguages.firstWhere(
        (language) => language.idiomaID == resolvedID,
        orElse: () => supportedLanguages.first,
      ).codigo;

      final idioma = supportedLanguages.firstWhere(
        (language) => language.idiomaID == resolvedID || language.codigo == resolvedCode,
        orElse: () => supportedLanguages.first,
      );

      _selectedLanguage = idioma;
      currentLanguageCode = idioma.codigo;
      currentIdiomaId = idioma.idiomaID;
      notifyListeners();
      return;
    }

    _selectedLanguage = supportedLanguages.first;
    currentLanguageCode = supportedLanguages.first.codigo;
    currentIdiomaId = supportedLanguages.first.idiomaID;
  }
}
